service: WebAPISample

provider:
  name: aws
  runtime: dotnetcore1.0

  stage: dev
  region: us-east-1

package:
  artifact: WebAPI/bin/Release/netcoreapp1.0/publish/deploy-package.zip

functions:
  WebAPI:
    handler: WebAPI::WebAPI.LambdaFunction::FunctionHandlerAsync
    events:
      - http:
          path: /{proxy+}
          method: any